
home_desc: 站在AI「人工智能」浪潮的风口，我们可以更好地应对未来的挑战!!
server_name: "0.0.0.0"
server_port: 9090

# AI模型相关参数
ChatGLMHandler:
  llm_model_path: model_weights/chatglm/chatglm2-6b-int4
  num_gpus: 2
  trust_remote_code: true
  init_model_when_start_server: false

WhisperHandler:
  model_name: large-v3
  model_dir: ./model_weights/whisper
  device: 'cuda:0'
  init_model_when_start_server: false
  language_map: {
    "普通话": "zh",
    "英语": "en",
  }

GPTHandler:
  api_url: null

FastSAMHandler:
  fastsam_model_path: /mnt/d/ai_dev/FastSAM/weights/FastSAM-x.pt
  device: 'cuda:0'

SAMHandler:
  model_ckpt: /mnt/d/ai_dev/ProPainter/weights/sam_vit_h_4b8939.pth
  model_type: vit_h
  device: 'cuda:1'

InpaintingHandler: 
  propainter_ckpt: /mnt/d/ai_dev/ProPainter/weights/ProPainter.pth
  raft_ckpt: /mnt/d/ai_dev/ProPainter/weights/raft-things.pth
  flow_completion_ckpt: /mnt/d/ai_dev/ProPainter/weights/recurrent_flow_completion.pth
  device: 'cuda:1'
  use_half: true

TrackerHandler:
  cutie_ckpt: /mnt/d/ai_dev/ProPainter/weights/cutie-base-mega.pth
  device: 'cuda:0'


EdgeTTSHandler:
  output_dir: /tmp
